### ISSUE TITLE
yaml: line 7: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by spursy** [RisingStack/example-prometheus-nodejs#6]
➜  prometheus-data git:(master) ✗ promtool test  rules alert.rules
Unit Testing:  alert.rules
  FAILED:
yaml: line 7: mapping values are not allowed in this context

How to fix this issue.

**Comment by ducmanh86** [comment]
you can update new config of `alert.rules` like below:
```
groups:
- name: PM2 Alert
  rules:
  - alert: APIHighMedianResponseTime
    expr: histogram_quantile(0.5, sum(rate(http_request_duration_ms_bucket[1m])) by (le, service, route, method)) > 100
    for: 60s
    annotations:
      summary: "High median response time on {{ $labels.service }} and {{ $labels.method }} {{ $labels.route }}"
      description: "{{ $labels.service }}, {{ $labels.method }} {{ $labels.route }} has a median response time above 100ms (current value: {{ $value }}ms)"
```
